# Temporary GitPage Host setup
title: Free Will
baseurl: "/ai"

# Theme settings
doks:
    color_theme: blue
    header:
        logo:
            text: Free Will
            image: false
        nav:
            - item_name: Machine Learning
              item_url: '/machine-learning'
            - item_name: Deep Learning
              item_url: '/deep-learning'
            - item_name: Computer Vision
              item_url: '/computer-vision'
            - item_name: NLP/Speech
              item_url: '/nlp-speech'
            - item_name: Reinforcement Learning
              item_url: '/reinforcement-learning'              
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2020. - Pedro Abundio Wang <br>All rights reserved.
        social_list:
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    links:
        machine-learning:
            icon:
            content: Machine Learning
            url: '/machine-learning'
            external_url: false
        deep-learning:
            icon:
            content: Deep Learning
            url: '/deep-learning'
            external_url: false
        computer-vision:
            icon:
            content: Computer Vision
            url: '/computer-vision'
            external_url: false
        nlp-speech:
            icon:
            content: NLP/Speech
            url: '/nlp-speech'
            external_url: false
        reinforcement-learning:
            icon:
            content: Reinforcement Learning
            url: '/reinforcement-learning'
            external_url: false